# Numpy Exercise 1

#### 1. Create a NumPy array a with values 1 through 9. Reshape the array to a 3x3 matrix.


In [39]:
import numpy as np

x=np.arange(1,10)
print("1D array :" ,x)

print("\n")

x.resize((3,3))
print("reshape 3x3 matrix: \n", x) # it is 2d matrixs 3 rows and 3 columns.

1D array : [1 2 3 4 5 6 7 8 9]


reshape 3x3 matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 2. Create a NumPy array b with values 5 through 13. Reshape the array to a 3x3 matrix.


In [40]:
b=np.arange(5,14)
print("1D array :",b)

print("\n")

b.resize((3,3))
print(" reshaped 3x3 array : \n", b)

1D array : [ 5  6  7  8  9 10 11 12 13]


 reshaped 3x3 array : 
 [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


#### 3. Multiply the matrix a by the matrix b using the @ operator.


In [43]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13]])

r=a @ b

print("matrix a : ")
print(a)
print("="*20)
print("matrix b : ")
print(b)
print("="*20)
print("multiplication of the matrix : ")
print(r)

matrix a : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix b : 
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
multiplication of the matrix : 
[[ 54  60  66]
 [126 141 156]
 [198 222 246]]


#### 4. Compute the dot product of the first row of a with the first column of b.


In [44]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13]])

r_a = a[0, :]
c_b = b[:, 0]
dot_product = np.dot(r_a, c_b)

print("matrix a : ")
print(a)
print("="*20)
print("matrix b : ")
print(b)
print("="*20)
print(f"1st row of a : {r_a}")
print(f"1st column of a : {c_b}")
print(f"Dot Product: {dot_product}")

matrix a : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix b : 
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
1st row of a : [1 2 3]
1st column of a : [ 5  8 11]
Dot Product: 54


#### 5. Compute the sum of all the elements in the matrix a.


In [45]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
total_sum = sum(sum(row) for row in a)

print(f"matrix a:")
for row in a:
    print(row)
print(f"sum of all elements :{total_sum}")    

matrix a:
[1 2 3]
[4 5 6]
[7 8 9]
sum of all elements :45


#### 6. Compute the product of all the elements in the matrix b.


In [2]:
import numpy as np

b = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13]])
product = np.prod(b)

print(f"matrix a:")
for row in b:
    print(row)
print(f"product of all elements :{product}")   

matrix a:
[5 6 7]
[ 8  9 10]
[11 12 13]
product of all elements :259459200


#### 7. Create a 1D NumPy array c with values [1, 2, 3, 4, 5]. Use the np.insert () function to insert the value 0 at index 2.


In [4]:
import numpy as np

c=np.array([1,2,3,4,5])

c_0=np.insert(c,2,0)

print("original 1D array c:")
print(c)
print("modified array:")
print(c_0)

original 1D array c:
[1 2 3 4 5]
modified array:
[1 2 0 3 4 5]


#### 8. Create a 1D NumPy array d with values [1, 2, 3, 4, 5]. Use the np.delete () function to delete the value at index 3.


In [7]:
import numpy as np

d=np.array([1,2,3,4,5])

d_delete=np.delete(d,3)

print("1D array:")
print(d)
print("deleted index 3 array :")
print(d_delete)

1D array:
[1 2 3 4 5]
deleted index 3 array :
[1 2 3 5]


#### 9. Create a 2D NumPy array e with dimensions 3x4 and values 1 through 12. Use boolean indexing to select all elements greater than 5.


In [9]:
import numpy as np

e = np.arange(1,13).reshape(3,4)

selected_elements = e[e > 5]

print("2D array e:")
print(e)
print("\n")
print("selected elements greater than 5:")
print(selected_elements)

2D array e:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


selected elements greater than 5:
[ 6  7  8  9 10 11 12]


#### 10. Create a 2D NumPy array f with dimensions 4x5 and values 1 through 20. Use fancy indexing to select the elements at positions at (0,0), (1,2), and (2,4).


In [13]:
import numpy as np

f=np.arange(1,21).reshape(4,5)

select_elements = f[[0,1,2],[0,2,4]]  # in this The first list [0, 1, 2] represents the row indices, and the second list [0, 2, 4] represents the column indices.

print("2D array f:")
print(f)
print("\n")
print("selected elements at position (0,0),(1,2),(2,4) are:")
print(select_elements)

2D array f:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


selected elements at position (0,0),(1,2),(2,4) are:
[ 1  8 15]


#### 11. Create a 2D NumPy array 'a' with dimensions 5x5 and values 0.5 in the diagonal and 0 elsewhere.


In [28]:
import numpy as np

a=np.eye(5)*0.5

print("2D array :") # eye returns a 2D array with ones on the diagonal and zeros elsewhere , so if * 0.5 with eye will give (1 * 0.5 = 0.5) 0.5 in diagonals.
print(a)

2D array :
[[0.5 0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.  0.5]]


#### 12. Create a 3D NumPy array b with dimensions 3x3x3 and random integer values between 0 and 10.

In [20]:
import numpy as np

b=np.random.randint(0,11,size=(3,3,3))

print("3D array b :")
print(b)

3D array b :
[[[ 6 10  4]
  [ 0  0  5]
  [ 7  3 10]]

 [[ 7  7  4]
  [ 2  2  1]
  [ 4  6  5]]

 [[ 1  4  6]
  [ 6  6  2]
  [ 2  2  3]]]


#### 13. Compute the mean of each row of the matrix b.


In [26]:
import numpy as np

row_means = np.mean(b,axis=1)

row_means_rounded = np.round(row_means, 2)

print("3D array b:")
print(b)
print("\n")
print("Mean of each row:")
print(row_means_rounded)

3D array b:
[[[ 6 10  4]
  [ 0  0  5]
  [ 7  3 10]]

 [[ 7  7  4]
  [ 2  2  1]
  [ 4  6  5]]

 [[ 1  4  6]
  [ 6  6  2]
  [ 2  2  3]]]


Mean of each row:
[[4.33 4.33 6.33]
 [4.33 5.   3.33]
 [3.   4.   3.67]]


#### 14. Compute the standard deviation of each column of the matrix 'a'.


In [32]:
import numpy as np

column_std=np.std(a,axis=0)

print("2D array a:")
print(a)
print("="*25)
print("Standard deviation of each column:")
print(column_std)

2D array a:
[[0.5 0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.  0.5]]
Standard deviation of each column:
[0.2 0.2 0.2 0.2 0.2]


#### 15. Compute the matrix multiplication of 'a' with its transpose.


In [39]:
import numpy as np

a_t=np.transpose(a)
result = np.dot(a,a_t)  # or result = a @ a_t

print("result of a*a^T:")
print(result)

result of a*a^T:
[[0.25 0.   0.   0.   0.  ]
 [0.   0.25 0.   0.   0.  ]
 [0.   0.   0.25 0.   0.  ]
 [0.   0.   0.   0.25 0.  ]
 [0.   0.   0.   0.   0.25]]


#### 16. Create a 2D NumPy array 'c' with dimensions 6x6 and values 1 in the diagonal and 0 elsewhere. Use the np.roll() function to shift the values in each row to the right by one position.


In [6]:
import numpy as np

c = np.eye(6)
c_shift = np.roll(c,shift=1,axis=1)

print("2D c array:")
print(c)
print("\n")
print("shifted array:")
print(c_shift)

2D c array:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


shifted array:
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]]


#### 17. Create a 2D NumPy array 'd' with dimensions 4x4 and random values between 0 and 1. Normalize the values in each row to have a sum of 1.


In [10]:
import numpy as np

d=np.random.rand(4,4)
row_sum = d.sum(axis=1)
d_normalized = d/row_sum[:, np.newaxis]   # The row_sums[:, np.newaxis] creates a new axis (column) from the row sums, allowing us to perform element-wise division.

print("2D d array")
print(d)
print("\n")
print("normalized array:")
print(d_normalized)

2D d array
[[0.4980468  0.00454985 0.25084176 0.4010905 ]
 [0.62762694 0.75584102 0.39506259 0.63387106]
 [0.38233343 0.67627541 0.22393111 0.8293884 ]
 [0.87683279 0.32197102 0.02320244 0.75215232]]


normalized array:
[[0.4313853  0.00394087 0.21726763 0.3474062 ]
 [0.26016686 0.31331476 0.16376319 0.2627552 ]
 [0.18103523 0.32021702 0.10603158 0.39271616]
 [0.4441552  0.16309278 0.01175308 0.38099894]]


#### 18. Create a 2D NumPy array 'e' with dimensions 3x3 and values 1 through 9. Use the np.flipud() function to flip the matrix vertically


In [17]:
import numpy as np

e = np.arange(1, 10).reshape(3, 3)
e_flipped = np.flipud(e)


print("e array:")
print(e)
print("\nFlipped e array:")
print(e_flipped)

e array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped e array:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 19. Create a 2D NumPy array with dimensions 4x4 and random integer values between 0 and 10. Sort the values in each row in ascending order.


In [16]:
import numpy as np

z = np.random.randint(0, 11,size=(4, 4))
z_sorted = np.sort(z,axis=1)


print("z array:")
print(z)
print("\nFlipped e array:")
print(z_sorted)

z array:
[[10  4  5  5]
 [ 8  4  8  2]
 [ 8  1 10  6]
 [ 9  8  8  6]]

Flipped e array:
[[ 4  5  5 10]
 [ 2  4  8  8]
 [ 1  6  8 10]
 [ 6  8  8  9]]


#### 20. Create a 2D NumPy array 'g' with dimensions 5x5 and values 0 in the diagonal and 1 elsewhere. Use the np.linalg.inv() function to compute the inverse of the matrix.

In [15]:
import numpy as np

g = 1-np.eye(5)
g_inverse = np.linalg.inv(g)

print("g array")
print(g)
print("\ninversed matrix")
print(g_inverse)

g array
[[0. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 0.]]

inversed matrix
[[-0.75  0.25  0.25  0.25  0.25]
 [ 0.25 -0.75  0.25  0.25  0.25]
 [ 0.25  0.25 -0.75  0.25  0.25]
 [ 0.25  0.25  0.25 -0.75  0.25]
 [ 0.25  0.25  0.25  0.25 -0.75]]
